
  CREATE TABLE "HR"."STUDENTMARKS" 
   (	"IDTEACHER" NUMBER(*,0), 
	"MATRICULE" VARCHAR2(30 BYTE), 
	"CIVILITY" VARCHAR2(3 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"SURNAME" VARCHAR2(50 BYTE), 
	"PHONE" NUMBER(*,0), 
	"MATRIMONIAL_SITUATION" VARCHAR2(7 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"IDCOURSE" NUMBER(*,0), 
	"ID_OPTION" NUMBER(*,0), 
	"ID_LEVEL" NUMBER(*,0), 
	"ID_TEACHER" NUMBER(*,0), 
	"CODE_COURSE" VARCHAR2(50 BYTE), 
	"LABEL_COURSE" VARCHAR2(100 BYTE), 
	"CREDIT_COURSE" NUMBER(*,0), 
	"ACADEMIC_YEAR" VARCHAR2(40 BYTE), 
	"IDREGISTRATE" NUMBER(*,0), 
	"ID_STUDENT" NUMBER(*,0), 
	"ID_COURSE" NUMBER(*,0), 
	"CA" NUMBER, 
	"EXAMEN" NUMBER, 
	"DATEREGISTRATION" NUMBER(*,0), 
	"IDSTUDENT" NUMBER(*,0), 
	"ID_OPTION_1" NUMBER(*,0), 
	"MATRICULE_1" VARCHAR2(40 BYTE), 
	"CIVILITY_1" VARCHAR2(3 BYTE), 
	"NAME_1" VARCHAR2(50 BYTE), 
	"SURNAME_1" VARCHAR2(50 BYTE), 
	"EMAIL_1" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
