
  CREATE TABLE "HR"."STUDENT" 
   (	"IDSTUDENT" NUMBER(*,0), 
	"ID_OPTION" NUMBER(*,0), 
	"MATRICULE" VARCHAR2(25 BYTE), 
	"CIVILITY" VARCHAR2(3 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"PHONE" NUMBER(*,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"LOGIN" VARCHAR2(30 BYTE), 
	"IDOPTION" NUMBER(*,0), 
	"CODE_OP" VARCHAR2(15 BYTE), 
	"LABEL_OP" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
